In [1]:
import numpy as np
import random as rd

In [2]:
# For dense probs

# Input
M = 40


baseprob = 1/M
Probs = np.zeros((M,M))

for k in range(M):
    oncemore = True
    while(oncemore):
        for l in range(M-1):
            Probs[k,l] = round(rd.gauss(1/M,sigma=0.01),5)
            if Probs[k,l] < 0 or Probs[k,l] > 1:
                oncemore = True
                break
            else:
                oncemore = False
        if not oncemore:
            Probs[k,M-1] = (1-np.sum(Probs[k,:M-1]))
            if Probs[k,M-1] < 0 or Probs[k,l] > 1:
                oncemore = True
# for k in range(N,M):
#     for l in range(M):
#         Probs[k,l] = 1/M
print(Probs)
np.save('Markov_M_'+str(M)+'_probs_dense_new',Probs)

[[0.03136 0.03815 0.01808 ... 0.02727 0.02216 0.00762]
 [0.01819 0.00408 0.02194 ... 0.0236  0.01955 0.06126]
 [0.01204 0.03318 0.03268 ... 0.01554 0.01933 0.0358 ]
 ...
 [0.0235  0.01451 0.03344 ... 0.0259  0.03127 0.00545]
 [0.02435 0.02355 0.0177  ... 0.0316  0.02875 0.04128]
 [0.03658 0.02195 0.02314 ... 0.01366 0.01559 0.1002 ]]


In [3]:
# For sparse probs

# Input
M = 40


Probs = np.zeros((M,M))

# n_clus = int(M/2)
n_clus = 10

clus_id = rd.choices(range(n_clus),[1]*n_clus,k=M)
clus = []
for c in range(n_clus):
    clus.append([])
for k in range(M):
    clus[clus_id[k]].append(k)

print(n_clus)
print(clus)

# for cl in clus:
#     outlinker = rd.choices(cl,[1]*len(cl),k=1)[0]

info = str(clus) + ' \n\n'
for cli in range(len(clus)):
    cl = clus[cli]
    if len(cl) == 0:
        continue
    if len(cl) == 1:
        while True:
            Probs[cl[0],cl[0]] = round(rd.gauss(1/(len(cl)+1),sigma=0.0001),5)
            if Probs[cl[0],cl[0]] > 0  and Probs[cl[0],cl[0]] < 1:
                break
        cli_next = (cli + 1)%n_clus
        while(len(clus[cli_next]) == 0):
            cli_next = (cli_next + 1)%n_clus
        Probs[cl[0],rd.choices(clus[cli_next],[1]*len(clus[cli_next]),k=1)[0]] = 1 - Probs[cl[0],cl[0]]
        print(cl, cl[0])
        info += str(cl) + ' ' + str(cl[0]) + ' \n'
        continue
    outlinker = rd.choices(cl,[1]*len(cl),k=1)[0]
    print(cl, outlinker)
    info += str(cl) + ' ' + str(outlinker) + ' \n'
    for k in cl:
        if k == outlinker:
            n_probs = len(cl)+1
        else:
            n_probs = len(cl)
        oncemore = True
        while(oncemore):
            temp = []
            for ki in range(n_probs-1):
                temp_prob = round(rd.gauss(1/n_probs,sigma=0.01),5)
                if temp_prob < 0 or temp_prob > 1:
                    oncemore = True
                    break
                else:
                    temp.append(temp_prob)
                    oncemore = False
            if not oncemore:
                temp_prob = (1-sum(temp))
                if temp_prob < 0 or temp_prob > 1:
                    oncemore = True
                else:
                    temp.append(temp_prob)
        for ki in range(len(cl)):
            Probs[k,cl[ki]] = temp[ki]
        if k == outlinker:
            cli_next = (cli + 1)%n_clus
            while(len(clus[cli_next]) == 0):
                cli_next = (cli_next + 1)%n_clus
            Probs[k,rd.choices(clus[cli_next],[1]*len(clus[cli_next]),k=1)[0]] = temp[-1]
        

# print(Probs)
print(Probs[0:8,0:8])
# for k in range(M):
#     info += '\n' + str(Probs[k])

for k in range(M):
    info += '\n ['
    for l in range(M):
        info += str(Probs[k][l]) + '\t'
    info += ']'
# info += '\n' + str(Probs)
# np.save('Markov_M_'+str(M)+'_probs_sparse',Probs)

10
[[12, 25, 27, 30, 32], [14], [3, 17, 29], [0, 8, 20, 24, 33], [5, 13, 34, 36], [6, 9, 28, 31, 35, 39], [7, 18, 26], [23, 37, 38], [2, 10, 15, 16, 19, 22], [1, 4, 11, 21]]
[12, 25, 27, 30, 32] 30
[14] 14
[3, 17, 29] 29
[0, 8, 20, 24, 33] 8
[5, 13, 34, 36] 34
[6, 9, 28, 31, 35, 39] 39
[7, 18, 26] 7
[23, 37, 38] 23
[2, 10, 15, 16, 19, 22] 22
[1, 4, 11, 21] 4
[[0.20822 0.      0.      0.      0.      0.      0.      0.     ]
 [0.      0.24494 0.      0.      0.26436 0.      0.      0.     ]
 [0.      0.      0.16751 0.      0.      0.      0.      0.     ]
 [0.      0.      0.      0.32819 0.      0.      0.      0.     ]
 [0.      0.18632 0.      0.      0.19141 0.      0.      0.     ]
 [0.      0.      0.      0.      0.      0.24154 0.      0.     ]
 [0.      0.      0.      0.      0.      0.      0.17176 0.     ]
 [0.      0.      0.      0.      0.      0.      0.      0.25174]]


In [4]:
np.save('Markov_M_'+str(M)+'_probs_sparse'+'_nclus_'+str(n_clus)+'_new',Probs)
with open('Markov_M_'+str(M)+'_probs_sparse'+'_nclus_'+str(n_clus)+'_info_new.txt','w') as f:
    f.write(info)